# Generated by Django 6.1 on 2026-09-15 20:24

from django.db import migrations


def seed_catalog_images(apps, schema_editor):
    Destination = apps.get_model("travel", "Destination")
    Hotel = apps.get_model("travel", "Hotel")
    TravelPackage = apps.get_model("travel", "TravelPackage")

    destination_images = {
        1: "destinations/Goa.jpg",
        2: "destinations/kasol.jpg",
        3: "destinations/manali.jpg",
        4: "destinations/Ooty.webp",
        5: "destinations/munnar.webp",
    }

    hotel_images = {
        1: "hotels/goa_beach_resort.jpg",
        2: "hotels/kasol_valley_resort.jpg",
        3: "hotels/manali.jpg",
        4: "hotels/Ooty.webp",
        5: "hotels/munnar.webp",
    }

    package_images = {
        1: "packages/Goa.jpg",
        2: "packages/kasol_valley_resort.jpg",
        3: "packages/manali.jpg",
        4: "packages/Ooty.webp",
        5: "packages/munnar.webp",
    }

    for item_id, image_path in destination_images.items():
        Destination.objects.filter(id=item_id).update(image=image_path)

    for item_id, image_path in hotel_images.items():
        Hotel.objects.filter(id=item_id).update(image=image_path)

    for item_id, image_path in package_images.items():
        TravelPackage.objects.filter(id=item_id).update(image=image_path)


def reverse_seed_catalog_images(apps, schema_editor):
    Destination = apps.get_model("travel", "Destination")
    Hotel = apps.get_model("travel", "Hotel")
    TravelPackage = apps.get_model("travel", "TravelPackage")

    Destination.objects.filter(id__in=[1, 2, 3, 4, 5]).update(image="")
    Hotel.objects.filter(id__in=[1, 2, 3, 4, 5]).update(image="")
    TravelPackage.objects.filter(id__in=[1, 2, 3, 4, 5]).update(image="")


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_catalog_images,
            reverse_seed_catalog_images,
        ),
    ]
